### ISSUE TITLE
This plugin seems not supporting 'base' option

### ISSUE THREAD

**Issue by darron1217** [nikalsh/vuepress-auto-sidebar#1]
This plugin seems not supporting 'base' option.
My Vuepress RootDir is `docs` but it scans real root path of my project.
```
Error: ENOTDIR: not a directory, scandir 'D:\stormWorkspace\it-asset-management\.gitignore'
    at Object.fs.readdirSync (fs.js:904:18)
```

**Comment by nikalsh** [comment]
Thanks for raising this issue. I've released a new version (1.0.6) which adds support for the base-option.

**Comment by ajitbohra** [comment]
@nikalsh  on the latest version 

```
Vuepress-auto-sidebar: Base option not found
```

unable to use the plugin!

**Comment by kriscarilloxyz** [comment]
+1

**Comment by 82amp** [comment]
+1
Issue is that the default documentation sets up project with all the actual project files (i.e. not package.json, .gitignore, node_modules, etc), in a sub-folder. When npm run executes "vuepress dev docs", it's building from the absolute project root, whereas the plugin expects to run with `process.cwd()` already set in the `/docs/` folder.

Thus, it actually fails to find `.vuepress/config.js`, and cannot read the base config (which is probably not valid here anyway).

A (very hacky) work around is to modify `node_module/vuepress-auto-sidebar/index.js`, and append `'/docs'` to the getRootDir function, e.g. `return path.resolve(process.cwd()+ '/docs');`

A better solution would be to do a deep scan to find `.vuepress/config.js`, and have a different parameter (e.g. not `base` as it impacts other runtime links in vuepress- perhaps a new param like `folderBase`) that specifies the name of the folder. 

Or, better yet, pull the parameter that vuepress dev|build was run with. e.g. `docs` in the case of `vuepress dev docs`


Edit: will submit as a PR...

index.js: 
```
getRootDir = function () { 
    const extraPath = (process.argv.length > 3) ? `/${process.argv[3]}` : '';
    return path.resolve(process.cwd() + extraPath);
};```

Edit 2: this is not necessary for the cli version, as the docs specify to run it from within the appropriate folder, so the `process.cwd()` will resolve as expected
